services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: >
      sh -c "while ! nc -z db 3306; do echo 'Waiting for MySQL...'; sleep 2; done &&
            python manage.py migrate &&
            gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --access-logformat '%(t)s \"%(r)s\" %(s)s %(b)s in %(L)s'"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: password
      DB_HOST: db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
